const loginPageTxt = 'Username and Password will\n' 'Automatically Generated by Global IT\n''Infosolution';


const description = "GIT infosolution is a IT company , We develop software mobile app for both android and iOS,  web app like E-commerce , social media , management with secure development assurity.";
const purpose = "To make enhanced and versatile products that make change towards solving current problems mainly based on Indian Education system, Management system.";
const products = 'Inquiry Management System,\n''Institute Management System,\n''Attendance System';
const achievements = 'More than 60 Partnerships,\n''150+ Regular clients';
const founded = "2019";

const noInternetStr="Please check internet connectivity";
const success = "success";

const dataNotAvailable = "Data is Not Available";
const noFeedback = "No feedback available";
const updationMessage = "Record Updated Successfully";


const loginPref = "LoginPrefrences";
const call = "Call";
const notificationSettings = "Notification Settings";
const smsService = "SMS Service";
const feedbackHistory = "Feedback History";
const upcomingDate = "Upcoming Date";
const status = "Status";
const feedBackHistory = "FeedBack History";
const addFeedbackHeader = "Add Feedback";
const upcomingDateHeader = "Select upcoming Date";