const loginPageTxt = 'Username and Password will\n' 'Automatically Generated by Global IT\n''Infosolution';

const description = "GIT infosolution is a IT company , We develop software mobile app for both android and iOS,  web app like E-commerce , social media , management with secure development assurity.";

const purpose = "To make enhanced and versatile products that make change towards solving current problems mainly based on Indian Education system, Management system.";
const products = 'Inquiry Management System,\n''Institute Management System,\n''Attendance System\n';
const achievements = 'More than 60 Partnerships,\n''150+ Regular clients';
const founded = "2019";
const noInternetStr="Please check internet connectivity";
const success = "success";

const loginPref = "LoginPrefrences";