const loginPageTxt = 'Username and Password will\n' 'Automatically Generated by Global IT\n''Infosolution';
const loginPref = "LoginPrefrences";

const description = "GIT infosolution is a IT company , We develop software mobile app for both android and iOS,  web app like E-commerce , social media , management with secure development assurity.";
const purpose = "To make enhanced and versatile products that make change towards solving current problems mainly based on Indian Education system, Management system.";
const products = 'Inquiry Management System,\n''Institute Management System,\n''Attendance System';
const achievements = 'More than 60 Partnerships,\n''150+ Regular clients';
const founded = "2019";

const noInternetStr="Please check internet connectivity";
const success = "success";

const dataNotAvailable = "Data is Not Available";
const danger = "danger";
const appName = "Global IT Inquiry";
const userImageUri = "https://static.vecteezy.com/system/resources/previews/036/280/650/original/default-avatar-profile-icon-social-media-user-image-gray-avatar-icon-blank-profile-silhouette-illustration-vector.jpg";
const backgroundWhatsapp = "assets/images/background_whatsapp.png";

const wp_phone_number = "91932800789";
const wp_account_id = "207125825810672";
const phone_number_id = "186089601256908";

const adminUserType = "Admin";

const branchIdStr = "branch_id";
const branchNameStr = "branch_name";
const branchAddressStr = "branch_address";
const branchStr = "branch";

const admin = 'Admin';
const idStr = "id";
const nameStr = "name";
const usernameStr = "username";
const imageStr = "image";
const userTypeStr = "user_type";
const statusStr = "status";

const noFeedback = "No feedback available";
const updationMessage = "Record Updated Successfully";


const call = "Call";
const notificationSettings = "Notification Settings";
const smsService = "SMS Service";
const feedbackHistory = "Feedback History";
const upcomingDate = "Upcoming Date";
const status = "Status";
const feedBackHistory = "FeedBack History";
const addFeedbackHeader = "Add Feedback";
const upcomingDateHeader = "Select upcoming Date";
const convertStudent = "Convert as student";



const cameraImageUri = "https://www.shutterstock.com/image-vector/camera-clipart-vector-illustration-photo-600nw-2479223569.jpg";
