const splashScreenImage = "assets/images/splashScreenImg.png";
const loginImage = "assets/images/loginImg.png";
const userImageUri = "assets/images/user.png";
const userImg= "assets/images/user_image.png";
const defaultUserImage = "assets/images/user_image.png";
const dashboardBackgroundImg = "assets/images/main_background.png";
const aboutUsLogo = "assets/images/logo_about_us.png";
const aboutUsOwnerImage = "assets/images/owner.png";
const logoutImg = "assets/images/logoutIcon.png";